# =-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=-=-=-=-=-=-=
# Automatic R script generated via easypar
# 2022-05-27 17:06:25
# =-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=-=-=-=-=-=-=
 
 easypar_generated_function = function(x, y){ 
  print(x, y) 
} 
 # EASYPAR Autogenerated R-code
if(sys.nframe() == 0L) {
   args = commandArgs(trailingOnly = TRUE)
   x = args[1]
   y = args[2]
print("\nInput parameters for the function\n")
   print(x)
   print(y)
   easypar_generated_function(x, y)
}
