# =-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=-=-=-=-=-=-=
# Automatic R script generated via easypar
# 2019-09-30 01:40:14
# =-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=-=-=-=-=-=-=
 
 easypar_generated_function = function(x, y){ 
  print(x, y) 
} 
 # EASYPAR Autogenerated R-code
if(sys.nframe() == 0L) {
   args = commandArgs()
   x = args[1]
   y = args[2]
   print(x)
   print(y)
   easypar_generated_function(x, y)
}
